### ISSUE TITLE
[Temperature & Humidity] Timed out

### ISSUE THREAD

**Issue by sambal0** [hannseman/homebridge-mi-hygrothermograph#118] opened 2020-10-27 22:15 UTC
Hi,

I'm using homebridge-mi-hygrothermograph 3.0.2 already a while since more than a year and the plugin is constantly loosing connection after a couple of minutes/hours. Only a restart of the homebridge helps until it causes the output again after a few minutes/hours:
```
[Temperature & Humidity] [xx:xx:xx:xx:xx:xx] Timed out, last update: 2020-10-26T07:38:48.702Z
```

Already tried a bunch of various types of configuration from other similar closed issues, but none helped.

### Expected Behavior

Homebridge should get regular updates from the Temperature & Humidity plugin without a time out.

### Current Behavior

Temperature & Humidity plugin constantly looses connection to homebridge after a while and homekit is showing no response.

### Steps to Reproduce (for bugs)

Already moved it a couple of times closer, even laid it down next to the Raspberry. As mentioned above, only a restart resets the connection for an uncertain period of time.

### Versions

- **homebridge**: 1.1.6
- **homebridge-mi-hygrothermograph**: 3.0.2
- **node**:       v12.19.0
- **OS**:         Raspbian GNU/Linux 9 (stretch)

### Configuration

```        
            "name": "Temperature & Humidity",
            "temperatureName": "Temperature",
            "humidityName": "Humidity",
            "accessory": "Hygrotermograph",
            "address": "xx:xx:xx:xx:xx:xx",
            "timeout": 15,
            "forceDiscovering": true,
            "forceDiscoveringDelay": 900,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "fakeGatoEnabled": true,
            "fakeGatoStoragePath": "/var/homebridge/"
```

### Homebridge Log / Command Output

```
[Temperature & Humidity] [xx:xx:xx:xx:xx:xx] Timed out, last update: 2020-10-26T07:38:48.702Z
```

**Comment by hannseman** [comment] 2020-11-08 19:58
Duplicate of https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/58 and as described in that issue the only known fix is to buy a newer Raspberry PI or try your luck with various bluetooth dongles. The issue is most likely caused by a bug in the raspberry pi firmware https://github.com/raspberrypi/firmware/issues/1150#issuecomment-510483643.

FYI I just upgraded to an RPI4 and everything works just fine with the built in BLE.

**Closed by hannseman** 2020-11-08 19:58 UTC

**Comment by sambal0** [comment] 2020-11-11 21:50
> Duplicate of #58 and as described in that issue the only known fix is to buy a newer Raspberry PI or try your luck with various bluetooth dongles. The issue is most likely caused by a bug in the raspberry pi firmware [raspberrypi/firmware#1150 (comment)](https://github.com/raspberrypi/firmware/issues/1150#issuecomment-510483643).
> 
> FYI I just upgraded to an RPI4 and everything works just fine with the built in BLE.

Thanks a lot for your reply and the provided link. Read the whole thread and a simple firmware update was also mentioned as a possible solution. I updated the firmware of my RPI3 and voila - it worked! Everything has been going well since then. 👍
