### ISSUE TITLE
Readings not showing after updating to Mac OS Mojave 

### ISSUE THREAD

**Issue by lay55** [hannseman/homebridge-mi-hygrothermograph#24] opened 2018-09-25 21:27 UTC
Trying to install it on Mac OS mojave

Pasting my full log here:

Registering platform 'homebridge-config-ui-x.config'
[9/26/2018, 2:56:09 AM] ---
[9/26/2018, 2:56:09 AM] Loaded plugin: homebridge-mi-hygrothermograph
Error: Cannot find module 'xpc-connection'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/noble/lib/mac/highsierra.js:7:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by lay55** [comment] 2018-09-25 23:17
Managed to solve this but the temperature and humidity reading still not showing. running Homebridge on Mac OS Mojave...please help

**Comment by hannseman** [comment] 2018-09-26 07:45
Hi! Looks like the Bluetooth-library this plugin is using does not yet support MacOS Mojave. See https://github.com/noble/noble/pull/804.

I'll follow the issue in noble and release an update if needed as soon as Mojave support is available.

**Comment by BillS11** [comment] 2018-10-14 12:47
Thanks @hannseman for building this. I'm also using Mojave so will wait for the update once support is available. Cheers!

**Comment by lay55** [comment] 2019-01-04 09:20
Any update on macOS Mojave?

**Comment by hannseman** [comment] 2019-01-21 16:12
@lay55 there was some effort on the noble-repository to create a maintained fork which brings support for Node 10 as that too currently is broken. 

I've opened an issue in that repository about bringing in macOS Mojave support: https://github.com/abandonware/noble/issues/4. Unfortunately I haven't gotten any response yet.

**Comment by hannseman** [comment] 2019-01-26 19:52
I've also opened an issue on noble-mac to check if they are interested in depending on the @abandonware-fork. https://github.com/Timeular/noble-mac/issues/23

This would enable us to get support for both Mojave and Node 10 on linux.

**Comment by hannseman** [comment] 2019-02-21 15:36
An update on what's going on:

There's an open PR on `@abandonware/noble`. Looks like the author wants a vote for adding MacOS-support so please go in and add a :)

**Comment by hannseman** [comment] 2019-04-15 19:08
If you still are interested in running this on MacOS Mojave I can inform you that https://github.com/abandonware/noble/pull/8 have been merged. I'll try update to this new version ASAP.

**Comment by BillS11** [comment] 2019-04-15 22:48
Yes please!!! :)

**Comment by hannseman** [comment] 2019-04-18 21:26
I just released version `2.2.0` which brings support for MacOS Mojave. Please give it a try and tell me if it works so we can finally close this issue :-)

**Comment by BillS11** [comment] 2019-04-19 00:19
Just installed and confirmed working. Christmas has come very early! 
Thank you so much!!!

**Comment by hannseman** [comment] 2019-04-19 19:14
@BillS11 great to hear that! Thanks for the patience. 😄

**Closed by hannseman** 2019-04-19 19:14 UTC
