### ISSUE TITLE
No Sensor Data - Not responding

### ISSUE THREAD

**Issue by Tapsel99** [hannseman/homebridge-mi-hygrothermograph#161] opened 2021-10-16 16:33 UTC
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3. Received 5
    at new NodeError (internal/errors.js:322:7)
    at boundsError (internal/buffer.js:85:9)
    at checkBounds (internal/buffer.js:54:5)
    at checkInt (internal/buffer.js:73:3)
    at writeU_Int16LE (internal/buffer.js:721:3)
    at Buffer.writeUInt16LE (internal/buffer.js:729:10)
    at Hci.writeAclDataPkt (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/hci.js:487:9)
    at AclStream.write (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/acl-stream.js:28:13)
    at Gatt.writeAtt (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:175:19)
    at Gatt._queueCommand (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:200:12)

**Comment by hannseman** [comment] 2021-10-31 19:25
Duplicate of https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/125

**Closed by hannseman** 2021-10-31 19:25 UTC
