### ISSUE TITLE
Unsupppported state or unable to authenticate data - cipher.sh

### ISSUE THREAD

**Issue by maddinek** [hannseman/homebridge-mi-hygrothermograph#138] opened 2021-02-25 16:08 UTC
Hi there,

I tried to add my LYWSD03MMC sensors. I also added the bindKey. But I always get this error message:

> [Temperature & Humidity] Error: Unsupported state or unable to authenticate data
>     at Decipheriv.final (internal/crypto/cipher.js:174:29)
>     at Parser.decryptPayload (/usr/lib/node_modules/homebridge-mi-hygrothermograph/lib/parser.js:191:14)
>     at Parser.parse (/usr/lib/node_modules/homebridge-mi-hygrothermograph/lib/parser.js:59:12)
>     at Scanner.parseServiceData (/usr/lib/node_modules/homebridge-mi-hygrothermograph/lib/scanner.js:171:52)
>     at Scanner.onDiscover (/usr/lib/node_modules/homebridge-mi-hygrothermograph/lib/scanner.js:92:25)
>     at Noble.emit (events.js:327:22)
>     at Noble.onDiscover (/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/noble.js:196:10)
>     at NobleBindings.emit (events.js:315:20)
>     at NobleBindings.onDiscover (/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:169:10)
>     at Gap.emit (events.js:315:20)

Did someone have a similar issue or knows where it comes from?

My config:

>             "accessory": "Hygrotermograph",
>             "name": "Temperature & Humidity",
>             "address": "macaddress",
>             "timeout": 15,
>             "temperatureName": "Temperature",
>             "humidityName": "Humidity",
>             "fakeGatoEnabled": true,
>             "bindKey": "bindkey"

I'm running
node -v v14.16.0
and Raspbian GNU/Linux 10 (buster)

Cheers,
Martin

**Comment by hannseman** [comment] 2021-04-17 15:45
Duplicate of https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/101

**Closed by hannseman** 2021-04-17 15:45 UTC
