### ISSUE TITLE
RangeError after few minutes of running homebridge

### ISSUE THREAD

**Issue by RSMBS** [hannseman/homebridge-mi-hygrothermograph#47] opened 2019-03-25 07:40 UTC
after a few minutes of my running homebridge on my raspberry pi 3b it crashes with following errors

### Versions
homebridge version: 0.4.46
homebridge-mi-hygrothermograph: 2.1.0
node: 9.9.0  

### Configuration
config.json
"accessories": [
        {
            "accessory": "Hygrotermograph",
            "name": "Temperature & Humidity"
        },

### Homebridge Log / Command Output

RangeError [ERR_INDEX_OUT_OF_RANGE]: Index out of range
    at checkOffset (buffer.js:1015:11)
    at Buffer.readUInt16LE (buffer.js:1063:5)
    at Gap.onHciLeAdvertisingReport (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/gap.js:149:31)
    at Hci.emit (events.js:180:13)
    at Hci.processLeAdvertisingReport (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/hci.js:651:10)
    at Hci.processLeMetaEvent (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/hci.js:608:10)
    at Hci.onSocketData (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/hci.js:479:12)
    at BluetoothHciSocket.emit (events.js:180:13)

**Comment by hannseman** [comment] 2019-03-25 21:24
Hi, thanks for your report. This error isn't really related to this plugin but to the library which is used to read the bluetooth data. I looked around a bit and found this issue https://github.com/noble/noble/issues/381.

From what I can read there might be some bluetooth device in proximity that emits invalid advertisement packages. 

Could you please try and remove the battery from the temperature sensor and let this plugin run anyway. If you still see this error we can verify that it is something else than the Xiaomi Sensor that is causing the crash.

**Comment by RSMBS** [comment] 2019-03-27 19:16
Hello,
First of all thanks for the fast reply!!
i removed the battery from the temperature sensor and no error occured.
so i changed my config and now and wrote in the adress of the sensor. (so there shouldnt be anny conflicts with other bluetooth devices - think so :D )
it seems to work with the adress so im closing the issue!

best regards

**Comment by hannseman** [comment] 2019-04-15 19:01
Hi sorry for the late reply! Okay so this essentially rules out issues in how data is parsed by this plugin. I found a couple of errors in the noble library that this plugin use that feels related:
https://github.com/noble/noble/issues/241
https://github.com/noble/noble/issues/381
https://github.com/noble/noble/issues/405

I think the best approach might be to try and identify the rouge device that is transmitting the bad data and remote it from the range of the Raspberry PI. You can use `sudo hcitool lescan` to find other BLE devices within range and try to rule stuff out by power them off / removing them from range.

As the noble library is not actively maintained at the moment there's not much I can do to help you but hopefully the community can start fixing bugs in this library again by forks like https://github.com/abandonware/noble. I'll close this issue for now as this is not directly related to the code in this plugin but please get back to me if you find the cause as it's quite intriguing.

**Closed by hannseman** 2019-04-15 19:01 UTC
