### ISSUE TITLE
Crash during startup

### ISSUE THREAD

**Issue by shtirlic** [hannseman/homebridge-mi-hygrothermograph#6] opened 2018-04-03 18:13 UTC
```
[4/3/2018, 6:11:47 PM] ERROR LOADING PLUGIN homebridge-mi-hygrothermograph:
[4/3/2018, 6:11:47 PM] /usr/lib/node_modules/homebridge-mi-hygrothermograph/index.js:9
  );
  ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:65:22)
[4/3/2018, 6:11:47 PM] ====================
```

node --version
v6.12.2

**Comment by hannseman** [comment] 2018-04-04 05:47
Hi! Thanks for your report. The cause of this error is the trailing comma in the function call. Apparently this was supported syntax first in node 8.

I’ll fix this and get back to you. 

Hopefully this is the only issue with node 6. The support for node <8 is a bit experimental ATM. I had to disable running the test suite with node 6 on Travis CI since it started segfaulting for some unclear reason. 

- Hannes

**Comment by shtirlic** [comment] 2018-04-04 10:07
Thank you for clarification, updated to node 8 and everything is working good now.
Also I found that if I put address in upper case it's not working.

**Comment by hannseman** [comment] 2018-04-04 10:13
Thanks! Good catch! Opened issue #7 regarding the address not working as uppercase.

**Comment by hannseman** [comment] 2018-04-04 11:13
Fixed the issue with trailing commas on function calls and we now run the test suite with Node 6 on Travis CI. Closing this issue as the plugin should work on Node 6 again.

**Closed by hannseman** 2018-04-04 11:13 UTC
