### ISSUE TITLE
Problem with two Noble homebridge plugins

### ISSUE THREAD

**Issue by to0b** [hannseman/homebridge-mi-hygrothermograph#10] opened 2018-04-10 17:46 UTC
Hey,

I'm running your Plugin together with this https://github.com/honkmaster/homebridge-mi-flower-care/ Plugin. 

Both Plugins work standalone very fine but when homebridge is launched with both, then I don't get the current values from the devices.

Here is an output from the log:
`[2018-4-10 19:17:13] [Temperature & Humidity] Error: Unknown event type: 525
at Parser.parseEventData (/usr/lib/node_modules/homebridge-mi-hygrothermograph/lib/parser.js:155:15)
at Parser.parse (/usr/lib/node_modules/homebridge-mi-hygrothermograph/lib/parser.js:51:23)
at Scanner.onDiscover (/usr/lib/node_modules/homebridge-mi-hygrothermograph/lib/scanner.js:49:47)
at Noble.emit (events.js:180:13)
at Noble.onDiscover (/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/noble/lib/noble.js:178:10)
at NobleBindings.emit (events.js:180:13)
at NobleBindings.onDiscover (/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/noble/lib/hci-socket/bindings.js:174:10)
at Gap.emit (events.js:180:13)
at Gap.onHciLeAdvertisingReport (/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/noble/lib/hci-socket/gap.js:256:10)
at Hci.emit (events.js:180:13)
at Hci.processLeAdvertisingReport (/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/noble/lib/hci-socket/hci.js:651:10)
at Hci.processLeMetaEvent (/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/noble/lib/hci-socket/hci.js:608:10)
at Hci.onSocketData (/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/noble/lib/hci-socket/hci.js:479:12)
at BluetoothHciSocket.emit (events.js:180:13)
`

Do you have any idea how to get both plugins working?

**Comment by to0b** [comment] 2018-04-10 18:00
I've already tried this. Both mac addresses are specified.

**Comment by hannseman** [comment] 2018-04-10 18:11
Hmm that's weird. Could you turn on debug-logging for homebridge and copy the output? Either run homebridge with the -D flag or start with together with the environment variable DEBUG=*. 

 It would help a lot to have the actual service data for debugging.

One theory could be that that there is some interference caused by that homebridge-mi-flower-care actually connects to the device and this plugin just listens on the broadcasted advertise data.

**Comment by to0b** [comment] 2018-04-10 18:46
Here it is :)

[noble.zip](https://github.com/hannseman/homebridge-mi-hygrothermograph/files/1895971/noble.zip)

**Comment by to0b** [comment] 2018-04-10 20:16
I've tried to recreate the error but now it's gone. Previously I've splitted the plugins in two different homebridge instances with two different configs. The log file from above is with both plugins in one instance. 

Now I've splitted the plugins again but the error doesn't appear. But it seems that the values from both devices aren't updated in HomeKit. 

This archive includes the logs from both hb instances. 
[hygro.zip](https://github.com/hannseman/homebridge-mi-hygrothermograph/files/1896283/hygro.zip)

**Comment by to0b** [comment] 2018-04-10 20:35
Ok the reading from your Plugin works correctly. The values are being updated in HK. Only the flower Values aren't up to date.

**Comment by hannseman** [comment] 2018-04-11 18:11
Okay. Thanks for trying, if you happen to be able to recreate the error together with debug-logging enabled please get back to me. I'm going to try and get hold of a flower care device and see if I can recreate this myself.

I'll leave this issue open.

**Comment by honkmaster** [comment] 2018-04-22 12:58
Hi, I am the "developer" of the flower-care plugin, which is a fork of another plugin with some additions. I am not very firm with nodeJS right now and thus not able to dive deep into bugfixing. However, please tell me if I can still help.

**Comment by hannseman** [comment] 2018-09-17 19:30
Closing this as intercepting data from flower care devices are handled gracefully since [v1.6.0](https://github.com/hannseman/homebridge-mi-hygrothermograph/releases/tag/v1.6.0).

**Closed by hannseman** 2018-09-17 19:30 UTC
