### ISSUE TITLE
Error: Error: Unsupported state or unable to authenticate data

### ISSUE THREAD

**Issue by mackam93032** [hannseman/homebridge-mi-hygrothermograph#178] opened 2022-04-14 21:30 UTC
I have update latest version but still prompt below error message.
How can i fix it?
Thanks.

[15/4/2022, 5:22:00 am] [Temperature & Humidity-2] Error: Unsupported state or unable to authenticate data
    at Decipheriv.final (internal/crypto/cipher.js:174:29)
    at Parser.decryptPayload (/usr/lib/node_modules/homebridge-mi-hygrothermograph/lib/parser.js:189:14)
    at Parser.parse (/usr/lib/node_modules/homebridge-mi-hygrothermograph/lib/parser.js:59:12)
    at Scanner.parseServiceData (/usr/lib/node_modules/homebridge-mi-hygrothermograph/lib/scanner.js:174:52)
    at Scanner.onDiscover (/usr/lib/node_modules/homebridge-mi-hygrothermograph/lib/scanner.js:95:25)
    at Noble.emit (events.js:400:28)
    at Noble.onDiscover (/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/noble.js:213:10)
    at NobleBindings.emit (events.js:400:28)
    at NobleBindings.onDiscover (/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:188:10)
    at Gap.emit (events.js:400:28)

**Comment by hannseman** [comment] 2022-04-19 12:01
Duplicate of https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/178

**Closed by hannseman** 2022-04-19 12:01 UTC

**Comment by ndrobac** [comment] 2022-09-14 14:04
@hannseman you marked this as a duplicate of itself. Can you please take another look, I'm having the same issue, so any help would be appreciated.
